[workspace]
members = [
    "firnas_std",
    "firnas_vm",
    "firnas_tokenizer",
    "firnas_cli",
    "firnas_bytecode",
    "firnas_compiler",
    "firnas_interpreter",
    "firnas_ext",
    "firnas_runtime",
]
